package ec.app.testar;

public enum AvailableReturnTypes {
    AND, CLICKACTION, DRAGACTION, DRAGACTIONSAVAILABLE, EQUALS, EQUALSTYPE, ESCAPE, GREATERTHAN,
    HITKEYACTION, IFTHENELSE, LEFTCLICKSAVAILABLE, NOT, NUMBEROFACTIONS, NUMBEROFACTIONSOFTYPE,
    NUMBEROFDRAGACTIONS, NUMBEROFLEFTCLICKS, NUMBEROFPREVIOUSACTIONS, NUMBEROFTYPEACTIONS,
    NUMBEROFUNEXECUTEDDRAGACTIONS, NUMBEROFUNEXECUTEDLEFTCLICKS, NUMBEROFUNEXECUTEDTYPEACTIONS, OR,
    PREVIOUSACTION, RANDOMACTION, RANDOMACTIONOFTYPE, RANDOMACTIONOFTYPEOTHERTHAN, RANDOMLEASTEXECUTEDACTION,
    RANDOMMOSTEXECUTEDACTION, RANDOMNUMBER, RANDOMUNEXECUTEDACTION, RANDOMUNEXECUTEDACTIONOFTYPE,
    STATEHASNOTCHANGED, TYPEACTION, TYPEACTIONSAVAILABLE, TYPEOFACTIONOF, A, B, C, D, E, F, G, H,
    I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, d1, d2, d3, d4, d5, d6, d7, d8
}
